// <auto-generated />
using System;
using AuctionService.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuctionService.Dal.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    partial class AuctionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuctionService.Domain.Entities.Auction", b =>
                {
                    b.Property<long>("AuctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuctionId"));

                    b.Property<long>("ArtworkId")
                        .HasColumnType("bigint");

                    b.Property<string>("ArtworkName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SellerUserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("StartPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long?>("WinnerUserId")
                        .HasColumnType("bigint");

                    b.HasKey("AuctionId");

                    b.HasIndex("EndTime");

                    b.HasIndex("SellerUserId");

                    b.HasIndex("Status");

                    b.HasIndex("WinnerUserId");

                    b.ToTable("Auctions", (string)null);

                    b.HasData(
                        new
                        {
                            AuctionId = 1L,
                            ArtworkId = 101L,
                            ArtworkName = "Starry Night Reproduction",
                            CurrentPrice = 1500.00m,
                            EndTime = new DateTime(2025, 11, 7, 11, 26, 54, 108, DateTimeKind.Utc).AddTicks(8460),
                            SellerUserId = 1L,
                            StartPrice = 1000.00m,
                            StartTime = new DateTime(2025, 10, 31, 11, 26, 54, 108, DateTimeKind.Utc).AddTicks(8460),
                            Status = 1
                        },
                        new
                        {
                            AuctionId = 2L,
                            ArtworkId = 102L,
                            ArtworkName = "Mona Lisa Copy",
                            CurrentPrice = 3500.00m,
                            EndTime = new DateTime(2025, 11, 4, 11, 26, 54, 108, DateTimeKind.Utc).AddTicks(8460),
                            SellerUserId = 2L,
                            StartPrice = 2000.00m,
                            StartTime = new DateTime(2025, 10, 26, 11, 26, 54, 108, DateTimeKind.Utc).AddTicks(8460),
                            Status = 2,
                            WinnerUserId = 4L
                        },
                        new
                        {
                            AuctionId = 3L,
                            ArtworkId = 103L,
                            ArtworkName = "Abstract Art #5",
                            CurrentPrice = 500.00m,
                            EndTime = new DateTime(2025, 11, 10, 11, 26, 54, 108, DateTimeKind.Utc).AddTicks(8460),
                            SellerUserId = 3L,
                            StartPrice = 500.00m,
                            StartTime = new DateTime(2025, 11, 3, 11, 26, 54, 108, DateTimeKind.Utc).AddTicks(8460),
                            Status = 1
                        },
                        new
                        {
                            AuctionId = 4L,
                            ArtworkId = 104L,
                            ArtworkName = "Modern Sculpture",
                            CurrentPrice = 5000.00m,
                            EndTime = new DateTime(2025, 11, 3, 11, 26, 54, 108, DateTimeKind.Utc).AddTicks(8460),
                            SellerUserId = 1L,
                            StartPrice = 3000.00m,
                            StartTime = new DateTime(2025, 10, 29, 11, 26, 54, 108, DateTimeKind.Utc).AddTicks(8460),
                            Status = 2,
                            WinnerUserId = 5L
                        },
                        new
                        {
                            AuctionId = 5L,
                            ArtworkId = 105L,
                            ArtworkName = "Landscape Painting",
                            CurrentPrice = 800.00m,
                            EndTime = new DateTime(2025, 11, 12, 11, 26, 54, 108, DateTimeKind.Utc).AddTicks(8460),
                            SellerUserId = 4L,
                            StartPrice = 800.00m,
                            StartTime = new DateTime(2025, 11, 6, 11, 26, 54, 108, DateTimeKind.Utc).AddTicks(8460),
                            Status = 0
                        });
                });

            modelBuilder.Entity("AuctionService.Domain.Entities.Bid", b =>
                {
                    b.Property<long>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BidId"));

                    b.Property<long>("AuctionId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("BidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("BidId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("Bids", (string)null);

                    b.HasData(
                        new
                        {
                            BidId = 1L,
                            AuctionId = 1L,
                            BidAmount = 1100.00m,
                            Timestamp = new DateTime(2025, 11, 1, 11, 26, 54, 108, DateTimeKind.Utc).AddTicks(8460),
                            UserId = 2L
                        },
                        new
                        {
                            BidId = 2L,
                            AuctionId = 1L,
                            BidAmount = 1300.00m,
                            Timestamp = new DateTime(2025, 11, 2, 11, 26, 54, 108, DateTimeKind.Utc).AddTicks(8460),
                            UserId = 3L
                        },
                        new
                        {
                            BidId = 3L,
                            AuctionId = 1L,
                            BidAmount = 1500.00m,
                            Timestamp = new DateTime(2025, 11, 3, 11, 26, 54, 108, DateTimeKind.Utc).AddTicks(8460),
                            UserId = 4L
                        },
                        new
                        {
                            BidId = 4L,
                            AuctionId = 2L,
                            BidAmount = 2500.00m,
                            Timestamp = new DateTime(2025, 10, 28, 11, 26, 54, 108, DateTimeKind.Utc).AddTicks(8460),
                            UserId = 3L
                        },
                        new
                        {
                            BidId = 5L,
                            AuctionId = 2L,
                            BidAmount = 3500.00m,
                            Timestamp = new DateTime(2025, 10, 29, 11, 26, 54, 108, DateTimeKind.Utc).AddTicks(8460),
                            UserId = 4L
                        },
                        new
                        {
                            BidId = 6L,
                            AuctionId = 4L,
                            BidAmount = 3500.00m,
                            Timestamp = new DateTime(2025, 10, 30, 11, 26, 54, 108, DateTimeKind.Utc).AddTicks(8460),
                            UserId = 2L
                        },
                        new
                        {
                            BidId = 7L,
                            AuctionId = 4L,
                            BidAmount = 5000.00m,
                            Timestamp = new DateTime(2025, 10, 31, 11, 26, 54, 108, DateTimeKind.Utc).AddTicks(8460),
                            UserId = 5L
                        });
                });

            modelBuilder.Entity("AuctionService.Domain.Entities.Payment", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("AuctionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PaymentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransactionStatus")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("PaymentId");

                    b.HasIndex("AuctionId")
                        .IsUnique();

                    b.HasIndex("TransactionStatus");

                    b.HasIndex("UserId");

                    b.ToTable("Payments", (string)null);

                    b.HasData(
                        new
                        {
                            PaymentId = 1L,
                            Amount = 3500.00m,
                            AuctionId = 2L,
                            PaymentTime = new DateTime(2025, 11, 4, 13, 26, 54, 108, DateTimeKind.Utc).AddTicks(8460),
                            TransactionStatus = 1,
                            UserId = 4L
                        },
                        new
                        {
                            PaymentId = 2L,
                            Amount = 5000.00m,
                            AuctionId = 4L,
                            PaymentTime = new DateTime(2025, 11, 3, 14, 26, 54, 108, DateTimeKind.Utc).AddTicks(8460),
                            TransactionStatus = 1,
                            UserId = 5L
                        });
                });

            modelBuilder.Entity("AuctionService.Domain.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            Balance = 10000.00m,
                            UserName = "john_doe"
                        },
                        new
                        {
                            UserId = 2L,
                            Balance = 15000.00m,
                            UserName = "jane_smith"
                        },
                        new
                        {
                            UserId = 3L,
                            Balance = 8000.00m,
                            UserName = "bob_wilson"
                        },
                        new
                        {
                            UserId = 4L,
                            Balance = 20000.00m,
                            UserName = "alice_brown"
                        },
                        new
                        {
                            UserId = 5L,
                            Balance = 12000.00m,
                            UserName = "charlie_davis"
                        });
                });

            modelBuilder.Entity("AuctionService.Domain.Entities.Auction", b =>
                {
                    b.HasOne("AuctionService.Domain.Entities.User", "Seller")
                        .WithMany("SellerAuctions")
                        .HasForeignKey("SellerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuctionService.Domain.Entities.User", "Winner")
                        .WithMany("WonAuctions")
                        .HasForeignKey("WinnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Seller");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("AuctionService.Domain.Entities.Bid", b =>
                {
                    b.HasOne("AuctionService.Domain.Entities.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionService.Domain.Entities.User", "User")
                        .WithMany("Bids")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuctionService.Domain.Entities.Payment", b =>
                {
                    b.HasOne("AuctionService.Domain.Entities.Auction", "Auction")
                        .WithOne("Payment")
                        .HasForeignKey("AuctionService.Domain.Entities.Payment", "AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionService.Domain.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuctionService.Domain.Entities.Auction", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("AuctionService.Domain.Entities.User", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Payments");

                    b.Navigation("SellerAuctions");

                    b.Navigation("WonAuctions");
                });
#pragma warning restore 612, 618
        }
    }
}
